### ISSUE TITLE
enter flows to the tables by the controllers 

### ISSUE THREAD

**Issue by ali64Mon** [P4ELTE/t4p4s#3]
Hi,

Could you please tell me how I can add a new flow for a table with a match key consisted of multiple fields, each one having a different match type?

Regards,
Alireza

**Comment by nissos** [comment]
Hey,

i am currently investigating the software switch for performance reasons. Therefor. i have had a deep look into the source code. I can describe to you, what you probably have to do since i did not test your special case yet (only running a simple custom p4 program).

To understand how you can add things to the table, you first have to understand how controllers work and how you can modify them. 

### How does the controller work and communicate with my programm?

Basically, if you start your t4p4s switch with your own written p4 program (different tables etc.), a socket for controller communication is being opened. The controller will be executed in an own process (if you kill your t4p4s switch with ctrl+c, it will still be there! Be cautious: If you want to start another P4 program with another controller, it will use the previous controller, unless you kill the controller process!).

Responsible for the switch side of the socket is the backend. So, between the backend and the controller messages are being exchanged and handled. The necessary source files you need to know for that are in "t4p4s/src/hardware_dep/shared/ctrl_plane/". 
The great strength of P4 lies in the ability of dynamically filling those tables. For the default t4p4s switch this is not the case! I assume, that with the experimental P4RuntimeAPI ([](https://github.com/P4ELTE/P4RuntimeAPI)) for t4p4s this feature is being added, but i haven't tested this for now as well. 
The default t4p4s implementation uses a more static controller: At the start of the controller a configuration file is being read in (you can give that option by starting the switch with the option ctrcfg=path/to/file) and for each t4p4s switch instance, which connects to the socket, the init commands are being executed. 

### How can i write my own controller for my own program?

At first, understand how controllers and the main program are connected. If you are not familiar with this switch and only tried the %l2fwd test, have a look into " t4p4s/examples.cfg ". Here you can see, what options are taken for l2fwd (reference to t4p4s description in this repo). Important for the controller are these two options: 
`ctr=l2fwd    ctrcfg=examples/l2fwd_table.txt `
The first option tells, which controller to take and the second option, which config file to take. Very important for the first option is, that it references to a file named  "dpdk_l2fwd_controller.c" in the directory "t4p4s/src/hardware_dep/shared/ctrl_plane/". So you have to create a new file there named "dpdk_name_controller.c" and copy the l2fwd controller example. Make sure to add the new file to the Makefile in the same directory (just copy and adapt one of the examples)! Now you can run the l2fwd example with your controller by taking the option "ctr=name".

**Modify the standard controller to fit for your program**
If you look at the code, you have several things to do (I won't go too much into detail here):
- Adapt the method, which reads the config file in and change the config file/stick to this pattern!
- Adapt init() method to fill your tables with entries and default actions.

**Now, we come to the answer of your question, how to fill the tables.** I'd recommend to adapt the example fill methods (i.e. fill_dmac_table with the input params read in from config file). But what is happening there?

At first, a bunch of variables are declared. And this is, where it becomes important. What basically will be done is that you send a message to the socket. The message is stored in the buffer variable and has a fixed length. Be careful, not to add too much or change the buffer size! Otherwise things might not be added to the message! What happens now is basically filling the buffer with input:
       
        ```
        h = create_p4_header(buffer, 0, 2048);
        te = create_p4_add_table_entry(buffer,0,2048);
        strcpy(te->table_name, "dmac_0");
```
te contains a p4 header and our buffer now looks like this: [(p4_header h) (p4_add_table_entry te) ...].
h contains information about the p4 version, message length etc., te the table name and number of matching params (see t4p4s/src/hardware_dep/shared/ctrl_plane/messages.h).

        ```
        exact = add_p4_field_match_exact(te, 2048);
        strcpy(exact->header.name, "ethernet.dstAddr");
        memcpy(exact->bitmap, mac, 6);
        exact->length = 6*8+0;
```

**Here, a key is being added (this is for your question!)**. Now, our buffer looks like [(p4_header h) (p4_add_table_entry te) (p4_action_parameter)...]. To add more of them now, just add this part of code as often as you need it , adapt the field match method in the first line (see t4p4s/src/hardware_dep/shared/ctrl_plane/messages.h), the header name, the bitmap and edit the length(!).

Afterwards, the associated action and the action params are added to the buffer, converted to the right endianness and the buffer is sent. Care about the buffer size! Also, there might be a maximal param limit!

So, i hope you now have a better insight on how controllers work and how to fill your own tables.
